when:
  - event: [ push, manual ]
    branch: main

steps:
  - name: generate docs
    image: archlinux:latest
    commands:
      - pacman-key --init
      - pacman-key --recv-keys E029EB9088C833C2
      - pacman-key --lsign-key E029EB9088C833C2
      - echo "[kotontrion]" >> /etc/pacman.conf
      - echo "Server = https://arch-pkgs.kotontrion.net/\$arch/" >> /etc/pacman.conf
      - pacman -Syu --noconfirm libastal-meta vala meson blueprint-compiler gobject-introspection libadwaita libportal dart-sass libnma-gtk4 git python-jinja python-magic python-markdown python-markupsafe python-typogrify
      - arch-meson build --wipe -Dbuild_target=docs --wrap-mode=default
      - meson compile -C build docs
  - name: deploy
    image: alpine/git
    environment:
      PAGES_TOKEN:
        from_secret: pages_token
    commands:
      - git config --global user.email "$CI_COMMIT_AUTHOR_EMAIL"
      - git config --global user.name "[Woodpecker CI] $CI_COMMIT_AUTHOR"
      - git clone -b pages https://$PAGES_TOKEN@codeberg.org/$CI_REPO pages
      - find pages -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -r {} +
      - mv build/docs/libkompass/* pages
      - cd pages
      - git add --all
      - git diff --cached --quiet || git commit -m "[CI SKIP] Deploy docs from $CI_REPO_URL/commit/$CI_COMMIT_SHA"
      - git push https://$PAGES_TOKEN@codeberg.org/$CI_REPO pages
